Import numpy and pandas.

In [1]:
import pandas as pd
import numpy as np
import select as something
pd.set_option('display.max_columns', 54)

Using the bash magic command, view the list of files inside of the data directory.

In [13]:
%ls -lrt data

total 17824
-rw-r--r--  1 mtessema  staff  8577108 Mar 23 14:43 ActiveFile-Wilm1thru8-20191015.csv
-rw-r--r--  1 mtessema  staff   543729 Mar 23 14:43 DE-VoterFile-Documentation 20171010.pdf

Load the csv file into a Pandas DataFrame.

In [14]:
# # Create DataFrame here.
df_voters = pd.read_csv("/Users/mtessema/DataEngineering.Labs.RegisteredVotersFileWilmingtonDE/data/ActiveFile-Wilm1thru8-20191015.csv", skipinitialspace=True, engine='python')

Display a list of columns in the DataFrame.

In [4]:
df_voters.columns

Index(['UNIQUE-ID', 'LAST-NAME', 'FIRST-NAME', 'MID-INIT', 'SUFFIX',
       'YEAR-OF-BIRTH', 'HOME-NO', 'HOME-APT', 'HOME-STREET', 'HOME-DEV',
       'HOME-CITY', 'HOME-ZIPCODE', 'COUNTY', 'ED', 'RD', 'SD', 'CNLEVY',
       'WILM', 'CODE-HOME-CITY', 'SCH-DIST', 'PARTY', 'DATE-REG', 'PP-HIST-1',
       'PP-HIST-2', 'PR-HIST-1', 'PR-HIST-2', 'PR-HIST-3', 'GEN-HIST-1',
       'GEN-HIST-2', 'GEN-HIST-3', 'GEN-HIST-4', 'GEN-HIST-5', 'SP-HIST-1',
       'SP-HIST-2', 'SP-HIST-3', 'SCHL-HIST-1', 'SCHL-HIST-2', 'SCHL-HIST-3',
       'SCHL-HIST-4', 'SCHL-HIST-5', 'REF-HIST-1', 'REF-HIST-2', 'REF-HIST-3',
       'REF-HIST-4', 'REF-HIST-5', 'MAIL-NO', 'MAIL-APT', 'MAIL-STR',
       'MAIL-CITY', 'MAIL-STATE', 'MAIL-ZIP', 'DATE-LAST-CHG', 'CODE-CHANGE',
       'STATUS'],
      dtype='object')

What is the shape of this DataFrame? How many columns does each row have? How many rows are there?

In [5]:
df_voters.shape

(51909, 54)

# HOME ZIP CODE

Group objects using the HOME-ZIPCODE column. Assign the value to a variable called grouped_zc.  
[Pandas Groupby User Guide](https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html)

In [6]:
grouped_zc = df_voters.groupby('HOME-ZIPCODE')

In [7]:
grouped_zc

What type of object is grouped_zc?

In [8]:
type(grouped_zc)

pandas.core.groupby.generic.DataFrameGroupBy

DataFrameGroupBy objects contain a groups attribute. Display the value of the groups attribute belonging to the grouped_zc object.

In [9]:
grouped_zc.head()

,UNIQUE-ID,LAST-NAME,FIRST-NAME,MID-INIT,SUFFIX,YEAR-OF-BIRTH,HOME-NO,HOME-APT,HOME-STREET,HOME-DEV,HOME-CITY,HOME-ZIPCODE,COUNTY,ED,RD,SD,CNLEVY,WILM,CODE-HOME-CITY,SCH-DIST,PARTY,DATE-REG,PP-HIST-1,PP-HIST-2,PR-HIST-1,PR-HIST-2,PR-HIST-3,GEN-HIST-1,GEN-HIST-2,GEN-HIST-3,GEN-HIST-4,GEN-HIST-5,SP-HIST-1,SP-HIST-2,SP-HIST-3,SCHL-HIST-1,SCHL-HIST-2,SCHL-HIST-3,SCHL-HIST-4,SCHL-HIST-5,REF-HIST-1,REF-HIST-2,REF-HIST-3,REF-HIST-4,REF-HIST-5,MAIL-NO,MAIL-APT,MAIL-STR,MAIL-CITY,MAIL-STATE,MAIL-ZIP,DATE-LAST-CHG,CODE-CHANGE,STATUS
0,100234840,ROY,BEVERLY,A,NaN,1952,320,#912,E 5TH ST,HERLIHY HOUSE APTS,WILMINGTON,19801,N,1,2,3,10,4,NaN,CS,I,20010815,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20180715,CR,A
1,100685572,WILLIAMS,LISA,F,NaN,1968,826,NaN,W 5TH ST,NaN,WILMINGTON,19801,N,4,3,3,10,5,NaN,CS,D,19920810,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20180715,CR,A
2,100485262,HARRIS,JOSEPH,A,III,1963,2616,NaN,W 18TH ST,NaN,WILMINGTON,19806,N,3,4,1,4,8,NaN,RC,R,19960123,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20180715,CR,A
3,100349191,LAMBORN,GERALD,V,NaN,1958,706,NaN,W 34TH ST,NaN,WILMINGTON,19802,N,1,1,1,4,1,NaN,BR,D,19960624,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20190805,CR,A
4,100394887,KRYSTOPOLSKI,ANDREW,R,NaN,1981,1009,NaN,ANCHORAGE ST,NaN,WILMINGTON,19805,N,5,2,3,10,6,NaN,CS,D,20030730,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20180715,CR,A
5,100604371,CARTER,MILDRED,P,NaN,1923,2319,NaN,N PINE ST,NaN,WILMINGTON,19802,N,11,2,2,4,3,NaN,BR,D,19621000,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20180715,CR,A
6,100046407,VELEZ,EDISON,NaN,NaN,1939,1022,NaN,READ ST,NaN,WILMINGTON,19805,N,7,3,3,10,6,NaN,CS,D,20011207,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20180715,CR,A
7,100462556,DORSEY,BERNARD,S,NaN,1941,1521,NaN,MAPLE ST,NaN,WILMINGTON,19805,N,8,3,3,10,6,NaN,CS,I,19980120,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20180715,CR,A
8,100377694,KOVACH,KAREN,L,NaN,1966,8,NaN,S SCOTT ST,NaN,WILMINGTON,19805,N,8,3,3,10,6,NaN,CS,R,19921013,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20180715,CR,A
9,100537362,HARRIS,DAVID,B,NaN,1974,2616,NaN,W 18TH ST,NaN,WILMINGTON,19806,N,3,4,1,4,8,NaN,RC,I,19921014,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20180715,CR,A
10,100737992,WALLACE,JONATHAN,NaN,NaN,1968,920,#211,N MONROE ST,SACRED HEART VILLAGE,WILMINGTON,19801,N,6,2,3,4,4,NaN,CS,D,20060217,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20180715,CR,A
11,100664028,MCKENNIES,RON,T,NaN,1955,306,NaN,W 33RD ST,NaN,WILMINGTON,19802,N,2,1,2,4,1,NaN,BR,D,19920921,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20180715,CR,A
12,100234321,NORMAN,CELESTINE,H,NaN,1947,1307,NaN,N ORANGE ST,NaN,WILMINGTON,19801,N,3,2,2,4,4,NaN,RC,D,20000726,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20190924,CR,A
13,100248067,NORMAN,WILLIAM,L,3RD,1977,1307,NaN,N ORANGE ST,NaN,WILMINGTON,19801,N,3,2,2,4,4,NaN,RC,R,19980921,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20180715,CR,A
14,100574026,ORSIC,IVAN,A,NaN,1984,2116,NaN,GILLES ST,UNION PARK GARDENS,WILMINGTON,19805,N,2,3,3,10,7,NaN,RC,I,20020906,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20180715,CR,A
21,100761613,CLARK,JUSTIN,NaN,NaN,1988,2450,#4-C,N MARKET ST,NaN,WILMINGTON,19802,N,7,1,2,4,3,NaN,BR,D,20070112,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20180715,CR,A
28,100753375,AMBLARD,CEDRIC,J,NaN,1972,1100,#210,LOVERING AVE,PARK PLAZA CONDOS,WILMINGTON,19806,N,6,4,1,4,8,NaN,RC,I,20060926,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20180715,CR,A
29,100681410,PERKINS,JERRY,D,NaN,1939,701,NaN,COVERLY RD,BRANDYWINE HILLS,WILMINGTON,19802,N,1,1,1,4,1,NaN,BR,D,20030723,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20180715,CR,A
48,100016749,BALDWIN,BECKY,D,NaN,1970,1300,NaN,GILPIN AVE,NaN,WILMINGTON,19806,N,6,4,1,4,8,NaN,RC,D,20020801,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20180715,CR,A
83,100749412,CUTRONA,CHRISTOPHER,J,NaN,1988,1303,#1010,DELAWARE AVE,PARQ AT THE SQUARE,WILMINGTON,19806,N,6,4,1,4,8,NaN,RC,I,20060809,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20180715,CR,A
576,100251586,KLOCKO,ANDREA,L,NaN,1966,509,NaN,REDFERN AVE,NaN,WILMINGTON,19807,N,3,3,3,10,7,NaN,RC,I,19920822,0,0,0,0,0,0,0,0,0,1994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20180715,CR,A
3900,100449302,PULLELLA,LENA,C,NaN,1932,3101,NaN,SWARTHMORE RD,WESTMORLAND,WILMINGTON,19807,N,10,3,1,10,7,NaN,RC,I,19561000,0,0,0,0,0,0,0,0,0,2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20180715,CR,A
3901,100135479,ROBINSON,KRISTIN,L,NaN,1977,3211,NaN,SWARTHMORE RD,WESTMORLAND,WILMINGTON,19807,N,10,3,1,10,7,NaN,RC,D,20041005,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20181020,U,A
3902,100855116,ROBERTS,ELISABETH,M,NaN,1990,3223,NaN,SWARTHMORE RD,WESTMORLAND,WILMINGTON,19807,N,10,3,1,10,7,NaN,RC,R,20091019,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20180715,CR,A
3977,100837520,KENDLE,ALAN,M,NaN,1969,3215,NaN,FORDHAM RD,WESTMORLAND,WILMINGTON,19807,N,10,3,1,10,7,NaN,RC,I,20090220,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20181210,CR,A

Invoke the size method on the grouped_zc object to find out how many items are associated with each zip code.

In [10]:
  grouped_zc .size()

HOME-ZIPCODE
19801    10730
19802    17182
19805    15548
19806     8326
19807      123
dtype: int64

Use a magic command so that matplotlib graphics will display inline.

In [ ]:
%matplotlib inline

Create a pie chart illustrating the number of voters per zip code.

In [ ]:
# from matplotlib import pyplot as plt
# plot =grouped_zc.plot.pie(subplots='HOME-ZIPCODE', figsize='UNIQUE-ID')
labels = [df_voters[HOME-ZIPCODE]]
matplotlib.pyplot.pie(grouped_zc.size(), labels = labels)

# YEAR OF BIRTH

Group objects by the YEAR-OF-BIRTH column. Assign the value to an object called "grouped_yob".

In [15]:
grouped_yob = df_voters.groupby('YEAR-OF-BIRTH')

Display the value of the groups attribute belonging the grouped_yob object.

In [16]:
grouped_yob.head()

,UNIQUE-ID,LAST-NAME,FIRST-NAME,MID-INIT,SUFFIX,YEAR-OF-BIRTH,HOME-NO,HOME-APT,HOME-STREET,HOME-DEV,HOME-CITY,HOME-ZIPCODE,COUNTY,ED,RD,SD,CNLEVY,WILM,CODE-HOME-CITY,SCH-DIST,PARTY,DATE-REG,PP-HIST-1,PP-HIST-2,PR-HIST-1,PR-HIST-2,PR-HIST-3,GEN-HIST-1,GEN-HIST-2,GEN-HIST-3,GEN-HIST-4,GEN-HIST-5,SP-HIST-1,SP-HIST-2,SP-HIST-3,SCHL-HIST-1,SCHL-HIST-2,SCHL-HIST-3,SCHL-HIST-4,SCHL-HIST-5,REF-HIST-1,REF-HIST-2,REF-HIST-3,REF-HIST-4,REF-HIST-5,MAIL-NO,MAIL-APT,MAIL-STR,MAIL-CITY,MAIL-STATE,MAIL-ZIP,DATE-LAST-CHG,CODE-CHANGE,STATUS
0,100234840,ROY,BEVERLY,A,NaN,1952,320,#912,E 5TH ST,HERLIHY HOUSE APTS,WILMINGTON,19801,N,1,2,3,10,4,NaN,CS,I,20010815,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20180715,CR,A
1,100685572,WILLIAMS,LISA,F,NaN,1968,826,NaN,W 5TH ST,NaN,WILMINGTON,19801,N,4,3,3,10,5,NaN,CS,D,19920810,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20180715,CR,A
2,100485262,HARRIS,JOSEPH,A,III,1963,2616,NaN,W 18TH ST,NaN,WILMINGTON,19806,N,3,4,1,4,8,NaN,RC,R,19960123,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20180715,CR,A
3,100349191,LAMBORN,GERALD,V,NaN,1958,706,NaN,W 34TH ST,NaN,WILMINGTON,19802,N,1,1,1,4,1,NaN,BR,D,19960624,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20190805,CR,A
4,100394887,KRYSTOPOLSKI,ANDREW,R,NaN,1981,1009,NaN,ANCHORAGE ST,NaN,WILMINGTON,19805,N,5,2,3,10,6,NaN,CS,D,20030730,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20180715,CR,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22219,100737706,BROWN,BEULAH,NaN,NaN,1919,1005,#1012,N FRANKLIN ST,INGLESIDE APTS,WILMINGTON,19806,N,7,4,1,4,8,NaN,RC,D,20060206,0,0,0,0,0,0,0,0,2012,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20180715,CR,A
23508,101151582,MCNEIL,LOIS,R,NaN,1919,513,NaN,S HARRISON ST,NaN,WILMINGTON,19805,N,7,3,3,10,6,NaN,CS,D,20180802,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20180807,CR,A
42509,100435977,MATAS,ELEANOR,B,NaN,1919,1100,#1108,LOVERING AVE,NaN,WILMINGTON,19806,N,6,4,1,4,8,NaN,RC,D,19560901,0,0,2018,2016,0,2018,2016,0,2012,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20181116,VH,A
49249,101092654,KENNEDY,JORDAN,D,NaN,1900,724,NaN,N BANCROFT PKY,NaN,WILMINGTON,19805,N,2,3,3,10,7,NaN,RC,I,20161114,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20170731,P6,I
49808,100452120,RISPOLI,ANNA,M,NaN,1916,1005,#107,N FRANKLIN ST,INGLESIDE APTS,WILMINGTON,19806,N,7,4,1,4,8,NaN,RC,D,19560301,0,0,0,0,2002,0,0,0,0,2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20170331,P6,I

Select the object for the row indicating that the voter was born in 1900.

In [17]:

grouped_yob.get_group(1900)

,UNIQUE-ID,LAST-NAME,FIRST-NAME,MID-INIT,SUFFIX,YEAR-OF-BIRTH,HOME-NO,HOME-APT,HOME-STREET,HOME-DEV,HOME-CITY,HOME-ZIPCODE,COUNTY,ED,RD,SD,CNLEVY,WILM,CODE-HOME-CITY,SCH-DIST,PARTY,DATE-REG,PP-HIST-1,PP-HIST-2,PR-HIST-1,PR-HIST-2,PR-HIST-3,GEN-HIST-1,GEN-HIST-2,GEN-HIST-3,GEN-HIST-4,GEN-HIST-5,SP-HIST-1,SP-HIST-2,SP-HIST-3,SCHL-HIST-1,SCHL-HIST-2,SCHL-HIST-3,SCHL-HIST-4,SCHL-HIST-5,REF-HIST-1,REF-HIST-2,REF-HIST-3,REF-HIST-4,REF-HIST-5,MAIL-NO,MAIL-APT,MAIL-STR,MAIL-CITY,MAIL-STATE,MAIL-ZIP,DATE-LAST-CHG,CODE-CHANGE,STATUS
49249,101092654,KENNEDY,JORDAN,D,NaN,1900,724,NaN,N BANCROFT PKY,NaN,WILMINGTON,19805,N,2,3,3,10,7,NaN,RC,I,20161114,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20170731,P6,I

Graph a histogram to  illustrate the age distribution of voters in this dataset. Ty using different values for the bins attribute of the histogram.

In [18]:
df_voters['YEAR-OF-BIRTH'].plot(kind='hist', title='Rating');

# PARTY

Group objects using the PARTY column. Assign the value to a variable called grouped_p.

In [19]:
grouped_p = df_voters.groupby('PARTY')
grouped_p

Display the value of the groups attribute belonging to the grouped_p object.

In [20]:
grouped_p.head()

,UNIQUE-ID,LAST-NAME,FIRST-NAME,MID-INIT,SUFFIX,YEAR-OF-BIRTH,HOME-NO,HOME-APT,HOME-STREET,HOME-DEV,HOME-CITY,HOME-ZIPCODE,COUNTY,ED,RD,SD,CNLEVY,WILM,CODE-HOME-CITY,SCH-DIST,PARTY,DATE-REG,PP-HIST-1,PP-HIST-2,PR-HIST-1,PR-HIST-2,PR-HIST-3,GEN-HIST-1,GEN-HIST-2,GEN-HIST-3,GEN-HIST-4,GEN-HIST-5,SP-HIST-1,SP-HIST-2,SP-HIST-3,SCHL-HIST-1,SCHL-HIST-2,SCHL-HIST-3,SCHL-HIST-4,SCHL-HIST-5,REF-HIST-1,REF-HIST-2,REF-HIST-3,REF-HIST-4,REF-HIST-5,MAIL-NO,MAIL-APT,MAIL-STR,MAIL-CITY,MAIL-STATE,MAIL-ZIP,DATE-LAST-CHG,CODE-CHANGE,STATUS
0,100234840,ROY,BEVERLY,A,NaN,1952,320,#912,E 5TH ST,HERLIHY HOUSE APTS,WILMINGTON,19801,N,1,2,3,10,4,NaN,CS,I,20010815,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20180715,CR,A
1,100685572,WILLIAMS,LISA,F,NaN,1968,826,NaN,W 5TH ST,NaN,WILMINGTON,19801,N,4,3,3,10,5,NaN,CS,D,19920810,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20180715,CR,A
2,100485262,HARRIS,JOSEPH,A,III,1963,2616,NaN,W 18TH ST,NaN,WILMINGTON,19806,N,3,4,1,4,8,NaN,RC,R,19960123,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20180715,CR,A
3,100349191,LAMBORN,GERALD,V,NaN,1958,706,NaN,W 34TH ST,NaN,WILMINGTON,19802,N,1,1,1,4,1,NaN,BR,D,19960624,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20190805,CR,A
4,100394887,KRYSTOPOLSKI,ANDREW,R,NaN,1981,1009,NaN,ANCHORAGE ST,NaN,WILMINGTON,19805,N,5,2,3,10,6,NaN,CS,D,20030730,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20180715,CR,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17347,101072610,IADISERNIA,KATIE,R,NaN,1984,530,#2A,N LINCOLN ST,NaN,WILMINGTON,19805,N,9,3,3,10,7,NaN,RC,Y,20160706,0,0,0,0,0,0,2016,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20180715,CR,A
18075,101083789,GURKA,BRIAN,J,NaN,1990,1305,NaN,N CLAYTON ST,NaN,WILMINGTON,19806,N,7,4,1,4,8,NaN,RC,T,20160928,0,0,0,0,0,0,2016,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20180715,CR,A
18799,100946353,BROWN,BREANNA,T,NaN,1994,3111,NaN,N MADISON ST,NaN,WILMINGTON,19802,N,2,1,2,4,1,NaN,BR,T,20121012,0,0,0,0,0,0,2016,0,2012,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20190826,CR,A
19128,100380254,LUPI,PATRICIA,L,NaN,1971,512,NaN,N BROOM ST,NaN,WILMINGTON,19805,N,1,3,3,10,5,NaN,RC,M,19960813,0,0,0,0,0,0,2016,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20191011,CR,A
22522,101066289,NEILL,CHRISTOPHER,NaN,NaN,1985,900,#28,N BROOM ST,NaN,WILMINGTON,19806,N,9,4,3,4,5,NaN,RC,T,20160425,0,0,0,0,0,0,2016,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20180926,CR,A

Invoke the size method on the grouped_p object to find out how many items are associated with each party.

In [21]:
grouped_p.size()

PARTY
A       52
B      441
D    38020
E       30
G       42
H       82
I     7670
J      161
L       98
M        1
O       33
Q       17
R     4851
T       14
V       11
W      333
Y       14
Z       39
dtype: int64

Create a bar chart to visualize the number of voters associated with each party.

In [ ]:
grouped_p.plot.bar()

# Merging Two DataFrames

Using the data from the documentation, create a Pandas DataFrame that contains the party code and the corresponding legal name for each party.

In [ ]:
# legal_names = {}

In [ ]:
# df_legal_names = pd.DataFrame(legal_names)

In [ ]:
# df_legal_names

Create a Pandas DataFrame that contains the Party code and the corresponding number of registered voters for said party.

In [ ]:
# Create DataFrame df_party_counts here

In [ ]:
# df_party_counts

Merge the two DataFrames.

In [ ]:
# Merge DataFrame here

In [ ]:
# Display new DataFrame here

Create a bar graph again but using the legal name for each party as the value on the x axes.

In [ ]:
#